  deploy-production:
    name: Provision & Deploy to PRODUCTION
    needs: verify-dev
    runs-on: ubuntu-latest

    environment: production

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Verify PRODUCTION State
        run: |
          cd environments/prod
          terraform init -reconfigure

          echo "===== TERRAFORM STATE ====="
          terraform state list

          echo "===== TERRAFORM PLAN ====="
          terraform plan
